services:
  api:
    build: .
    container_name: docker_compose_api
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./test:/app/source/ #Add your docker-compose.yml source directory here.
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
